### ISSUE TITLE
2d array

### ISSUE THREAD

**Issue by ChousX** [JoshMcguigan/arr_macro#7]
It's not a fan of arr![ arr![ ... ; ...] ];

**Comment by JoshMcguigan** [comment]
Thanks for the comment. I could imagine having some `arr_2d![..]`, but I can't think of an implementation of this that would provide enough benefit to warrant the extra abstraction. Did you have any specific ideas?

**Comment by ChousX** [comment]
It was more of a slight quality of life improvement. If it would have any down sides for its current use case don't bother
