### ISSUE TITLE
Unable to use with locals inside another macro

### ISSUE THREAD

**Issue by drehren** [JoshMcguigan/arr_macro#8]
Hi! This crate does exactly what I need, but since I have many things into an array I wanted to put this inside a macro... turns out that the macro seems unable to find locals that the outer macro generates.. something like this:
```rust
macro_rules! expand{
    ([$t:ty; $l:literal]) => {{
        let mut i = 0;
        arr![<$t>::new({i += 1; i - 1}); $l]
    }}
}
```
This is just an example that triggers the issue 'cannot find value \`i\` in scope'.
I've created a repo where you can test the issue
https://github.com/drehren/rust_arr_macro_bug

**Comment by JoshMcguigan** [comment]
Hi @drehren thanks for the report. I'm not sure this is directly related to anything being done by `arr_macro`, but it is interesting nonetheless.

A minimal example (derived from your repo, thanks for posting) follows:

```rust
use arr_macro::arr;

struct MyStruct {
    data: u32,
}

impl MyStruct {
    fn new(data: u32) -> Self {
        Self { data }
    }
}

macro_rules! expand {
    ($t:ty) => {{
        let mut i = 0;
        arr![<$t>::new({i += 1; i - 1}); 3]
    }}
}

fn main() {
    let _ = expand!(MyStruct);
}
```

The above results in the following error:

```rust
$ cargo check
    Checking arr_issue v0.1.0 (/home/josh/workspace/rust_arr_macro_bug)
error[E0425]: cannot find value `i` in this scope
  --> src/main.rs:21:13
   |
21 |     let _ = expand!(MyStruct);
   |             ^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for mo
re info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `arr_issue`.

To learn more, run the command again with --verbose.
```

Surprisingly, if I modify the `expand` macro to hardcode the name of the struct the error goes away:

```rust
// modified expand macro that doesn't cause the error
macro_rules! expand {
    ($t:ty) => {{
        let mut i = 0;
        arr![MyStruct::new({i += 1; i - 1}); 3]
    }}
}
```

I know this modification makes the macro useless, I was just trying to minimize the example as much as I could. 

One additional interesting note is that if I use `cargo-expand` (by @dtolnay ) to expand the original code, the expanded version does compile without error.

**Comment by dtolnay** [comment]
This is https://github.com/rust-lang/rust/issues/43081. It should work if you use tokens instead of a type metavariable.

```rust
macro_rules! expand {
    ($($t:tt)*) => {{
        let mut i = 0;
        arr![<$($t)*>::new({i += 1; i - 1}); 3]
    }}
}
```

**Comment by drehren** [comment]
@JoshMcguigan I also thought that maybe it isn't an error of the macro per se, but I thought here would be a good place to ask about it...
@dtolnay Thank you! It worked with tokens
